<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Адрес',
    'Category' => 'Категории',
    'Cost' => 'Стоимость',
    'Count' => 'Количество',
    'Create Customer' => 'Добавить клиента',
    'Create Employee' => 'Добавить сотрудника',
    'Create Order' => 'Создать заказ',
    'Create P Category' => 'Добавить категорию товаров',
    'Create Product' => 'Добавить товар',
    'Create S Category' => 'Добавить категорию услуг',
    'Create Sales' => 'Добавить продажу',
    'Create Services' => 'Добавить услугу',
    'Customers' => 'Клиенты',
    'Date' => 'Дата',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Employee' => 'Сотрудник',
    'Employees' => 'Сотрудники',
    'First Name' => 'Имя',
    'Id Category' => 'Номер категории',
    'Id Customer' => 'Номер клиента',
    'Id Employee' => 'Номер сотрудника',
    'Id Order' => 'Номер заказа',
    'Id Sale' => 'Номер продажи',
    'Id Service' => 'Номер услуги',
    'Middle Name' => 'Отчество',
    'Name' => 'Название',
    'EName' => 'Имя сотрудника',
    'Order' => 'Заказ',
    'Orders' => 'Заказы',
    'P Categories' => 'Категории товаров',
    'Pcategory' => 'Категория товаров',
    'Phone' => 'Номер телефона',
    'Position' => 'Должность',
    'Product' => 'Товар',
    'Products' => 'Товары',
    'Reset' => 'Отменить',
    'S Categories' => 'Категории услуг',
    'Sales' => 'Продажи',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'Second Name' => 'Фамилия',
    'Service' => 'Услуга',
    'Services' => 'Услуги',
    'Status' => 'Статус',
    'Update' => 'Обносить',
    'Update Customer: {name}' => 'Обновить данные клиента: {name}',
    'Update Employee: {name}' => 'Обновить данные сотрудника: {name}',
    'Update Order: {name}' => 'Обновить данные заказа: {name}',
    'Update P Category: {name}' => 'Обновить данные категории товаров: {name}',
    'Update Product: {name}' => 'Обновить данные товара: {name}',
    'Update S Category: {name}' => 'Обновить данные категории услуг: {name}',
    'Update Sales: {name}' => 'Обновить данные продажи: {name}',
    'Update Services: {name}' => 'Обновить данные услуги: {name}',
    'Users' => 'Пользователи',
    'Analyses' => 'Анализ показателей',
    'Are you sure you want to delete this item?' => '',
    'Create Analyse' => 'Добавить запись',
    'ID' => '',
    'Month' => 'Месяц',
    'The requested page does not exist.' => '',
    'Update Analyse: {name}' => '',
    'Year' => 'Год',
    'Contents' => '@@Контент@@',
];
